name: "Pipeline CI/CD Workflow"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  integracao-continua:
    runs-on: ubuntu-latest
    env:
      FLASK_APP: src/app.py
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Instalando dependencias
        run: pip install -r requirements.txt
      - name: migrar banco de dados
        run: |
          flask db init 
          flask db migrate -m "Initial migration."
          flask db upgrade
      - name: Executando testes
        run: pytest -v --disable-warnings --maxfail=1
          
        
  # estagio01:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Olá mundo!
  #       run: echo "Olá, mundo!, Github Actions!"
  #     - name: "sleep"
  #       run: echo "echo estagio01"  
  # estagio02:
  #   needs: estagio01
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: "sleep"
  #       run: sleep 5
  # estagio03:
  #   needs: estagio02
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: "sleep"
  #       run: sleep 2      